# Generated by Django 4.1.7 on 2023-04-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='person',
            new_name='author',
        ),
    ]
